version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app/server
      - ./logs/docker.log:/app/docker.log
    environment:
      - FLASK_ENV=development
      - PORT=5001
      # Uncomment the next line to enable debug/verbose logging
      - FLASK_DEBUG=1
    command: ["sh", "/app/startup.sh"]

volumes:
  postgres_data: 