version: '3.8'

services:
  test-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
  
  test-redis:
    image: redis:7-alpine

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - POSTGRES_SERVER=test-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
      - REDIS_HOST=test-redis
      - REDIS_PORT=6379
      - TESTING=true
    depends_on:
      - test-db
      - test-redis
    command: >
      sh -c "/app/wait-for-it.sh test-db:5432 -t 30 -- /app/wait-for-it.sh test-redis:6379 -t 30 -- sh -c 'alembic upgrade head && pytest tests/ -v --cov=app --cov-report=html'"
    volumes:
      - ./logs:/app/logs
      - ./tests:/app/tests
      - ./htmlcov:/app/htmlcov

volumes:
  logs:
    driver: local 