"""Add foreign key constraint to campaigns.organization_id

Revision ID: c8480602e13f
Revises: 0145deaea857
Create Date: 2025-05-26 15:33:19.700973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8480602e13f'
down_revision: Union[str, None] = '0145deaea857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'campaigns', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    # ### end Alembic commands ###
