"""Add campaign_id to jobs table

Revision ID: cdebb3f7a0f1
Revises: bc5502513f8e
Create Date: 2025-05-26 02:17:36.768546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdebb3f7a0f1'
down_revision: Union[str, None] = 'bc5502513f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('campaign_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_jobs_campaign_id'), 'jobs', ['campaign_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_campaign_id'), table_name='jobs')
    op.drop_column('jobs', 'campaign_id')
    # ### end Alembic commands ###
