"""Add job_type to jobs table

Revision ID: d4e8f9a2b1c3
Revises: cdebb3f7a0f1
Create Date: 2025-05-26 02:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e8f9a2b1c3'
down_revision: Union[str, None] = 'cdebb3f7a0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the job type enum
    job_type_enum = sa.Enum(
        'FETCH_LEADS',
        'ENRICH_LEADS', 
        'VERIFY_EMAILS',
        'GENERATE_EMAIL_COPY',
        'UPLOAD_TO_INSTANTLY',
        'CLEANUP_CAMPAIGN',
        'GENERAL',
        name='jobtype'
    )
    job_type_enum.create(op.get_bind())
    
    # Add job_type column with default value
    op.add_column('jobs', sa.Column('job_type', job_type_enum, nullable=False, server_default='GENERAL'))
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_column('jobs', 'job_type')
    
    # Drop the enum type
    job_type_enum = sa.Enum(name='jobtype')
    job_type_enum.drop(op.get_bind())
    # ### end Alembic commands ### 