"""add delay_reason to jobs table

Revision ID: 18a1aeca9c27
Revises: 62605fd66cae
Create Date: 2025-05-25 01:54:58.282572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a1aeca9c27'
down_revision = '62605fd66cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delay_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('delay_reason')

    # ### end Alembic commands ###
