"""Remove count from campaigns

Revision ID: 30f0b9578e91
Revises: 97487eddd6f9
Create Date: 2025-05-12 21:21:24.865881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f0b9578e91'
down_revision = '97487eddd6f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
