"""Add error_details JSON column to Job model

Revision ID: 40048e325336
Revises: f6c2d90a4266
Create Date: 2025-05-12 20:11:57.736987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40048e325336'
down_revision = 'f6c2d90a4266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_details', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('error_details')

    # ### end Alembic commands ###
