"""add instantly_campaign_id to campaign

Revision ID: 62605fd66cae
Revises: 8d28c179ba56
Create Date: 2025-05-13 11:29:02.671514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62605fd66cae'
down_revision = '8d28c179ba56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instantly_campaign_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('instantly_campaign_id')

    # ### end Alembic commands ###
