"""add instantly_lead_create_success to lead model

Revision ID: 7fbcf61d007b
Revises: 25a9a785251e
Create Date: 2025-05-13 01:02:13.028158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbcf61d007b'
down_revision = '25a9a785251e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instantly_lead_create_success', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('instantly_lead_create_success')

    # ### end Alembic commands ###
