"""Replace searchUrl with fileName, totalRecords, url on Campaign model

Revision ID: a0f54c218407
Revises: ff9f0b80fe6d
Create Date: 2025-05-12 20:42:07.648795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f54c218407'
down_revision = 'ff9f0b80fe6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fileName', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('totalRecords', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('url', sa.Text(), nullable=False))
        batch_op.drop_column('searchUrl')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('searchUrl', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('url')
        batch_op.drop_column('totalRecords')
        batch_op.drop_column('fileName')

    # ### end Alembic commands ###
