"""change instantly_lead_create_success to instantly_lead_record json on lead model

Revision ID: bd7fbb69dab8
Revises: 7fbcf61d007b
Create Date: 2025-05-13 01:10:57.099030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7fbb69dab8'
down_revision = '7fbcf61d007b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instantly_lead_record', sa.JSON(), nullable=True))
        batch_op.drop_column('instantly_lead_create_success')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instantly_lead_create_success', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('instantly_lead_record')

    # ### end Alembic commands ###
