"""Add email_verification and enrichment_results to Lead

Revision ID: cca593e2b8d5
Revises: 
Create Date: 2025-05-11 13:13:29.072730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca593e2b8d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('enrichment_results', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('enrichment_results')
        batch_op.drop_column('email_verification')

    # ### end Alembic commands ###
