"""Add enrichment_job_id to Lead model

Revision ID: ff9f0b80fe6d
Revises: 40048e325336
Create Date: 2025-05-12 20:16:50.816993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9f0b80fe6d'
down_revision = '40048e325336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrichment_job_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('enrichment_job_id')

    # ### end Alembic commands ###
