from enum import Enum

class CampaignStatus(str, Enum):
    """Enum for campaign status values."""
    CREATED = 'CREATED'
    FETCHING_LEADS = 'FETCHING_LEADS'
    LEADS_FETCHED = 'LEADS_FETCHED'
    VERIFYING_EMAILS = 'VERIFYING_EMAILS'
    ENRICHING_LEADS = 'ENRICHING_LEADS'
    GENERATING_EMAILS = 'GENERATING_EMAILS'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED' 